---
- name: Set a-records in cloudflare
  community.general.cloudflare_dns:
    zone: "{{ main_domain }}"
    record: "{{ item }}"
    type: A
    value: "{{ ansible_host }}"
    ttl: 1
    proxied: false
    api_token: "{{ cf_api_token }}"
    solo: true
  loop:
    - "{{ main_domain }}"
    - "{{ xui_panel_domain }}"
    - "{{ ssh_domain }}"
    - "{{ sub_domain }}"

- name: Download cloudflare-warp gpg key
  ansible.builtin.get_url:
    url: https://pkg.cloudflareclient.com/pubkey.gpg
    dest: /tmp/cloudflare-warp.gpg
    mode: "0644"

- name: Dearmor cloudflare-warp gpg key
  ansible.builtin.command:
    cmd: gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg /tmp/cloudflare-warp.gpg
    creates: /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

- name: Add cloudflare-warp apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main"
    filename: cloudflare-client
    state: present

- name: Install cloudflare-warp
  ansible.builtin.apt:
    name: cloudflare-warp
    state: present
    update_cache: true

- name: Register cloudflare-warp
  ansible.builtin.command: warp-cli --accept-tos registration new
  changed_when: true
  failed_when: false

- name: Set cloudflare-warp mode to proxy
  ansible.builtin.command: warp-cli --accept-tos mode proxy
  changed_when: true

- name: Connect cloudflare-warp
  ansible.builtin.command: warp-cli --accept-tos connect
  changed_when: true
  notify:
    - Restart haproxy service
    - Restart x-ui service
